export const SHOPPING_LIST = [
  {
    id: 1,
    title: "벨트",
    price: 100000,
    category: "sports",
    img: "./img/health/belt.jpeg",
  },
  {
    id: 2,
    title: "바벨",
    price: 60000,
    category: "sports",
    img: "./img/health/babel.jpeg",
  },
  {
    id: 3,
    title: "덤벨",
    price: 30000,
    category: "sports",
    img: "./img/health/dumbbell.jpeg",
  },
  {
    id: 4,
    title: "턱걸이 기구",
    price: 80000,
    category: "sports",
    img: "./img/health/pull-up.jpeg",
  },
  {
    id: 5,
    title: "스트랩",
    price: 40000,
    category: "sports",
    img: "./img/health/strap.jpeg",
  },
  {
    id: 6,
    title: "에어팟 맥스",
    price: 600000,
    category: "tech",
    img: "./img/tech/airpod-max.jpeg",
  },
  {
    id: 7,
    title: "엔터키 배게",
    price: 15000,
    category: "tech",
    img: "./img/tech/enter-pillow.jpeg",
  },
  {
    id: 8,
    title: "아이맥",
    price: 1000000,
    category: "tech",
    img: "./img/tech/imac.jpeg",
  },
  {
    id: 9,
    title: "키보드",
    price: 90000,
    category: "tech",
    img: "./img/tech/keyboard.jpeg",
  },
  {
    id: 10,
    title: "마우스 패드",
    price: 10000,
    category: "tech",
    img: "./img/tech/mousepad.jpeg",
  },
  {
    id: 11,
    title: "버티컬 마우스",
    price: 120000,
    category: "tech",
    img: "./img/tech/vertical-mouse.jpeg",
  },
  {
    id: 12,
    title: "후드집업",
    price: 40000,
    category: "clothes",
    img: "./img/clothes/hooded-zip-up.jpeg",
  },
  {
    id: 13,
    title: "후드티",
    price: 30000,
    category: "clothes",
    img: "./img/clothes/hoodie.jpeg",
  },
  {
    id: 14,
    title: "조거팬츠",
    price: 35000,
    category: "clothes",
    img: "./img/clothes/jogger-pants.jpeg",
  },
  {
    id: 15,
    title: "패딩",
    price: 110000,
    category: "clothes",
    img: "./img/clothes/padding.jpeg",
  },
];
